-- AlterTable
ALTER TABLE "Shipment" ADD COLUMN "totalCompanyCharge" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Shipment" ADD COLUMN "agentProfit" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Shipment" ADD COLUMN "currency" TEXT NOT NULL DEFAULT 'INR';
